"""
clean.py — Build (8) Release Cleanup Script

Removes all development artifacts from the project directory so that
the resulting tree is suitable for creating a clean release ZIP.

After running this script:
  - No __pycache__ directories
  - No .pyc files
  - No .pytest_cache
  - No venv / .venv (machine-specific Python environments)
  - No aegis155.db (runtime database — regenerated by app on first start)
  - No *.log files
  - No *.bak / *.backup / *_backup files
  - No .env (must be configured from .env.example by the operator)
"""

import glob
import os
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))

def _remove_dir(path: str):
    if os.path.isdir(path):
        print(f"  [DEL DIR ] {path}")
        shutil.rmtree(path)

def _remove_file(path: str):
    if os.path.isfile(path):
        print(f"  [DEL FILE] {path}")
        os.remove(path)

def clean():
    print("=" * 60)
    print("  Build (8) Release Cleanup")
    print("=" * 60)

    # ------------------------------------------------------------------
    # 1. Remove virtual environments (machine-specific, must NOT ship)
    # ------------------------------------------------------------------
    print("\n[1] Removing virtual environments...")
    for venv_name in ("venv", ".venv"):
        _remove_dir(os.path.join(ROOT, venv_name))

    # ------------------------------------------------------------------
    # 2. Remove __pycache__ directories (all levels)
    # ------------------------------------------------------------------
    print("\n[2] Removing __pycache__ directories...")
    for dirpath, dirnames, _ in os.walk(ROOT, topdown=False):
        for d in dirnames:
            if d == "__pycache__":
                _remove_dir(os.path.join(dirpath, d))

    # ------------------------------------------------------------------
    # 3. Remove .pyc files (all levels)
    # ------------------------------------------------------------------
    print("\n[3] Removing .pyc files...")
    for pyc in glob.glob(os.path.join(ROOT, "**", "*.pyc"), recursive=True):
        _remove_file(pyc)

    # ------------------------------------------------------------------
    # 4. Remove .pytest_cache
    # ------------------------------------------------------------------
    print("\n[4] Removing .pytest_cache...")
    _remove_dir(os.path.join(ROOT, ".pytest_cache"))

    # ------------------------------------------------------------------
    # 5. Remove runtime database (app regenerates on first start via Alembic)
    # ------------------------------------------------------------------
    print("\n[5] Removing local runtime database...")
    _remove_file(os.path.join(ROOT, "aegis155.db"))
    _remove_file(os.path.join(ROOT, "aegis155.db-journal"))

    # ------------------------------------------------------------------
    # 6. Remove development/runtime logs
    # ------------------------------------------------------------------
    print("\n[6] Removing log files...")
    log_patterns = ["*.log", "backend*.log"]
    for pattern in log_patterns:
        for f in glob.glob(os.path.join(ROOT, pattern)):
            _remove_file(f)
        for f in glob.glob(os.path.join(ROOT, "**", pattern), recursive=True):
            _remove_file(f)

    # ------------------------------------------------------------------
    # 7. Remove backup / temporary files
    # ------------------------------------------------------------------
    print("\n[7] Removing backup and temporary files...")
    backup_patterns = ["*.bak", "*.backup", "*_backup", "*.tmp"]
    for pattern in backup_patterns:
        for f in glob.glob(os.path.join(ROOT, "**", pattern), recursive=True):
            _remove_file(f)

    # ------------------------------------------------------------------
    # 8. Remove .env (operator must configure from .env.example)
    #    .env.example is KEPT — it must contain only placeholders.
    # ------------------------------------------------------------------
    print("\n[8] Removing .env (keep .env.example)...")
    _remove_file(os.path.join(ROOT, ".env"))

    # ------------------------------------------------------------------
    # Verification pass
    # ------------------------------------------------------------------
    print("\n[VERIFY] Scanning for remaining artifacts...")
    issues = []

    for dirpath, dirnames, filenames in os.walk(ROOT):
        # Skip .git
        dirnames[:] = [d for d in dirnames if d != ".git"]
        for d in dirnames:
            if d in ("__pycache__", ".pytest_cache", "venv", ".venv"):
                issues.append(f"  REMAINING DIR: {os.path.join(dirpath, d)}")
        for f in filenames:
            fp = os.path.join(dirpath, f)
            if f.endswith(".pyc"):
                issues.append(f"  REMAINING PYC: {fp}")
            if f == "aegis155.db":
                issues.append(f"  REMAINING DB : {fp}")
            if f == ".env" and not f.endswith(".example"):
                issues.append(f"  REMAINING ENV: {fp}")

    print()
    if issues:
        print("[WARN] The following artifacts were NOT removed:")
        for i in issues:
            print(i)
        print()
    else:
        print("[OK] Repository is clean. Ready for release ZIP.")

    print("=" * 60)
    print("  Cleanup complete.")
    print("=" * 60)

if __name__ == "__main__":
    clean()
