"""Initial schema

Revision ID: 891f8b41578a
Revises: 
Create Date: 2026-09-23 08:23:48.366574

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '891f8b41578a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('representative_part', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('mass_g', sa.Float(), nullable=True),
    sa.Column('power_mw', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('alternative', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bom_items_component_id'), 'bom_items', ['component_id'], unique=False)
    op.create_index(op.f('ix_bom_items_id'), 'bom_items', ['id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_components_id'), 'components', ['id'], unique=False)
    op.create_index(op.f('ix_components_part_number'), 'components', ['part_number'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('power_subsystems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nominal_power_mw', sa.Float(), nullable=True),
    sa.Column('peak_power_mw', sa.Float(), nullable=True),
    sa.Column('duty_cycle_pct', sa.Float(), nullable=True),
    sa.Column('energy_mj', sa.Float(), nullable=True),
    sa.Column('conversion_efficiency', sa.Float(), nullable=True),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('evidence_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_subsystems_id'), 'power_subsystems', ['id'], unique=False)
    op.create_index(op.f('ix_power_subsystems_name'), 'power_subsystems', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('threshold', sa.String(), nullable=True),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_id'), 'requirements', ['id'], unique=False)
    op.create_index(op.f('ix_requirements_req_id'), 'requirements', ['req_id'], unique=True)
    op.create_table('simulation_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('frontend_version', sa.String(), nullable=True),
    sa.Column('backend_version', sa.String(), nullable=True),
    sa.Column('physics_version', sa.String(), nullable=True),
    sa.Column('hardware_revision', sa.String(), nullable=True),
    sa.Column('cad_revision', sa.String(), nullable=True),
    sa.Column('config_hash', sa.String(), nullable=True),
    sa.Column('result_hash', sa.String(), nullable=True),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.Column('configuration_snapshot', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_simulation_jobs_job_id'), 'simulation_jobs', ['job_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('configuration_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_id'), 'simulation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_run_id'), 'simulation_runs', ['run_id'], unique=True)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_id'), 'system_events', ['id'], unique=False)
    op.create_table('system_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frontend_version', sa.String(), nullable=True),
    sa.Column('backend_version', sa.String(), nullable=True),
    sa.Column('physics_version', sa.String(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.Column('hardware_revision', sa.String(), nullable=True),
    sa.Column('cad_revision', sa.String(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_versions_id'), 'system_versions', ['id'], unique=False)
    op.create_table('telemetry_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_sessions_id'), 'telemetry_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_sessions_session_id'), 'telemetry_sessions', ['session_id'], unique=True)
    op.create_table('test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('hardware_version', sa.String(), nullable=True),
    sa.Column('config', sa.String(), nullable=True),
    sa.Column('expected', sa.String(), nullable=True),
    sa.Column('observed', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_test_runs_test_id'), 'test_runs', ['test_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('result_data', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource'], unique=False)
    op.create_table('cad_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cad_models_id'), 'cad_models', ['id'], unique=False)
    op.create_table('requirement_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('evidence_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_evidence_id'), 'requirement_evidence', ['id'], unique=False)
    op.create_table('simulation_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_parameters_id'), 'simulation_parameters', ['id'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('cep50', sa.Float(), nullable=True),
    sa.Column('impact_x', sa.Float(), nullable=True),
    sa.Column('impact_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_id'), 'simulation_results', ['id'], unique=False)
    op.create_table('telemetry_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp_ms', sa.Integer(), nullable=True),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('voltage', sa.Float(), nullable=True),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('device_state', sa.String(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['telemetry_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_samples_id'), 'telemetry_samples', ['id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_telemetry_samples_id'), table_name='telemetry_samples')
    op.drop_table('telemetry_samples')
    op.drop_index(op.f('ix_simulation_results_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_simulation_parameters_id'), table_name='simulation_parameters')
    op.drop_table('simulation_parameters')
    op.drop_index(op.f('ix_requirement_evidence_id'), table_name='requirement_evidence')
    op.drop_table('requirement_evidence')
    op.drop_index(op.f('ix_cad_models_id'), table_name='cad_models')
    op.drop_table('cad_models')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_runs_test_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_telemetry_sessions_session_id'), table_name='telemetry_sessions')
    op.drop_index(op.f('ix_telemetry_sessions_id'), table_name='telemetry_sessions')
    op.drop_table('telemetry_sessions')
    op.drop_index(op.f('ix_system_versions_id'), table_name='system_versions')
    op.drop_table('system_versions')
    op.drop_index(op.f('ix_system_events_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_simulation_runs_run_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_simulation_jobs_job_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index(op.f('ix_requirements_req_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_power_subsystems_name'), table_name='power_subsystems')
    op.drop_index(op.f('ix_power_subsystems_id'), table_name='power_subsystems')
    op.drop_table('power_subsystems')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_components_part_number'), table_name='components')
    op.drop_index(op.f('ix_components_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_bom_items_id'), table_name='bom_items')
    op.drop_index(op.f('ix_bom_items_component_id'), table_name='bom_items')
    op.drop_table('bom_items')
    # ### end Alembic commands ###
